---
- name: Deploy Employee Management Application
  hosts: appserver
  become: yes

  tasks:

    - name: Create application directory
      file:
        path: /opt/employee-management
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml
      copy:
        src: files/docker-compose.yml
        dest: /opt/employee-management/docker-compose.yml

    - name: Pull latest Docker image
      command: docker compose pull
      args:
        chdir: /opt/employee-management

    - name: Start application
      command: docker compose up -d
      args:
        chdir: /opt/employee-management

    - name: Show running containers
      command: docker ps
      register: docker_ps

    - name: Display running containers
      debug:
        var: docker_ps.stdout_lines
